apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-node-pvc
  namespace: web-application
  labels:
    app: ipfs-node
spec:
  storageClassName: ipfs-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi