apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
  namespace: web-application
  labels:
    app: ipfs-service
spec:
  type: LoadBalancer
  ports:
    - name: "swarm"
      port: 4001
    - name: "api"
      port: 5001
    - name: "gateway"
      port: 8080
  selector:
    app: ipfs-node