apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: web-application
  labels:
    app: postgres
spec:
  storageClassName: postgres-local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"
