apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: web-application
  labels:
    app: postgres
spec:
  storageClassName: postgres-local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi