apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: web-application
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres