apiVersion: v1
kind: Service
metadata:
  name: library-service
  namespace: web-application
  labels:
    app: library
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 31005
  selector:
    app: library