apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-node-pv
  namespace: web-application
  labels:
    app: ipfs-node
spec:
  storageClassName: ipfs-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/ipfs"