CREATE ROLE admin_library WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:kBehkoa2/xm7QPCeRNU3Aw==$c+y9KzqELosUZqsVybClxYHvxgzvfQnmM78QoDnr2Zo=:ecNZp/ZDF9EzBsUO+SQ9QOiozvj05f1EU31sNSssVIg=';